#cloud-config
repo_update: false
repo_upgrade: none
runcmd:
  - |
  # Install Java
  - yum -y install java-1.8.0-openjdk-devel
  # /etc/bashrc setup
  - echo "Pentaho DI entries"
  - echo "export KETTLE_HOME=/home/ec2-user/" >> /etc/bashrc
